In [2]:
import torch

In [4]:
idx = torch.tensor([[0,5,6],[2,3,7],[1,2,3],[0,4,3]],dtype=torch.long)
src = torch.arange(32).reshape(4,-1)
print(idx)
print(src)

tensor([[0, 5, 6],
        [2, 3, 7],
        [1, 2, 3],
        [0, 4, 3]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])


In [6]:
torch.gather(src,1,idx)

tensor([[ 0,  5,  6],
        [10, 11, 15],
        [17, 18, 19],
        [24, 28, 27]])

In [4]:
from einops import reduce
a = torch.rand(4,5,6,2,3)
b = reduce(a,'a b c d e -> a b 1 d e', 'mean')
print(b.shape)

torch.Size([4, 5, 1, 2, 3])
